### PR TITLE
build nwperf with python3

### PR DESCRIPTION
**Pull request by dubmarm**

### CODE REVIEW

**Comment by karcaw** [comment]
Why all the spacing changes..  and they are not consistent..  and if that is needed they need to be in a separate 'whichspace standardization' PR, not in here with code changes.

**Comment by dubmarm** [comment]
i will create a separate PR for white space. However nwperf will fail to build on 2to3 changes alone due to incorrect spacing errors. Running `autopep8` resolved that issue.

**Comment by karcaw** [comment]
Hey ryan, any chance you can clean up the conflicts, and we can merge this?

**Comment by dubmarm** [comment]
I can look into it

**Pull request merged**
